import { Text, StyleSheet } from "react-native";

import { InfoCard } from "@/components/InfoCard";
import { QuerySurface } from "@/components/QuerySurface";
import { ScreenShell } from "@/components/ScreenShell";
import { colors, typography } from "@/lib/theme";

export default function ClinicalScreen() {
  return (
    <ScreenShell
      eyebrow="nodoctor.ng"
      title="Frontline health worker support."
      subtitle="Structured NSTG guidance for chemists, PPMVs, CHWs, and nurses. Assessment, treatment, referral, and dosing — grounded in evidence."
    >
      <InfoCard title="Dosing" accent="gold">
        <Text style={styles.copy}>
          Include patient weight in kg for dose calculations. Doses are calculated deterministically from NSTG formulas, not generated by AI.
        </Text>
      </InfoCard>
      <QuerySurface
        mode="clinical"
        initialQuery="Artemether-Lumefantrine dose for a 18 kg child"
        placeholder="E.g. Artemether-Lumefantrine dose for 18 kg child."
      />
    </ScreenShell>
  );
}

const styles = StyleSheet.create({
  copy: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: typography.body
  }
});

